CREATE TABLE IF NOT EXISTS users(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	email TEXT UNIQUE NOT NULL
);

DROP TABLE IF EXISTS orders;
CREATE TABLE orders(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER,
	total REAL,
	FOREIGN KEY(user_id) REFERENCES users(id)
);